# Generated by Django 5.1.2 on 2024-10-18 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título')),
                ('description', models.TextField(max_length=200, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('deadline', models.DateField(verbose_name='Fecha límite')),
                ('priority', models.CharField(blank=True, choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='B', max_length=1, verbose_name='Prioridad')),
                ('status', models.BooleanField(blank=True, choices=[('C', 'Completada'), ('E', 'En Progreso')], default='C', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
