# Generated by Django 5.1.2 on 2024-10-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=12, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(blank=True, choices=[('Completada', 'Completada'), ('En Progreso', 'En Progreso')], default='En Progreso', max_length=12, verbose_name='Estado'),
        ),
    ]
