# Generated by Django 5.1.2 on 2024-10-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='B', max_length=12, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('E', 'En Progreso'), ('C', 'Completada')], default='E', max_length=12, verbose_name='Estado'),
        ),
    ]
