# Generated by Django 5.1.2 on 2024-10-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='B', max_length=1, verbose_name='Prioridad'),
        ),
    ]
