# Generated by Django 5.1.2 on 2024-10-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('B', 'Baja'), ('A', 'Alta'), ('M', 'Media')], default='B', max_length=1, verbose_name='Prioridad'),
        ),
    ]
