# Generated by Django 5.1.2 on 2024-10-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='B', max_length=1, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Completada'), ('E', 'En Progreso')], default='E', max_length=12, verbose_name='Estado'),
        ),
    ]
