# Generated by Django 4.2.16 on 2024-10-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('M', 'Media'), ('B', 'Baja'), ('A', 'Alta')], default='B', max_length=1, verbose_name='Prioridad'),
        ),
    ]
