# Generated by Django 4.2.16 on 2024-10-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_description_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('A', 'Alta'), ('B', 'Baja'), ('M', 'Media')], default='B', max_length=1, verbose_name='Prioridad'),
        ),
    ]
