# Generated by Django 4.2.16 on 2024-11-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('M', 'Media'), ('B', 'Baja'), ('A', 'Alta')], default='B', max_length=1, verbose_name='Prioridad'),
        ),
    ]
